import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FooterMenu from "./component/footerMenu";
import HeaderBar from "./component/headerBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <HeaderBar />
        <div className="pb-20">
          {children}
        </div>
        <FooterMenu />
      </body>
    </html>
  );
}
